/**
 * Codegen: writes the source of src/db/cms-database.generated.ts — the object
 * that hands `{ open, tables }` (see steincms/cms/storage/db-contract.ts) into
 * createCms(). Called by generate-schemas.ts — not used at runtime.
 */

const GENERATED_BANNER =
	'// AUTO-GENERATED by npm run db:sync-schema — do not edit.\n// Source: src/content.schema.ts\n\n';

export function generateDbWiringSource(options: {
	listCollectionIds: string[];
	hasRegistrations: boolean;
}): string {
	const tableImports = [
		...options.listCollectionIds,
		...(options.hasRegistrations ? ['registrations'] : []),
		'singletons',
	];

	const tableEntries = tableImports.map((id) => `\t\t${id},`).join('\n');

	return `${GENERATED_BANNER}import type { CmsDatabase, DatabaseConnection } from '@steincms/cms/storage/db-contract';
import { getDb } from './client';
import { ${tableImports.join(', ')} } from './schema';

function openDatabase(): DatabaseConnection {
\treturn getDb() as unknown as DatabaseConnection;
}

export const cmsDatabase: CmsDatabase = {
\topen: openDatabase,
\ttables: {
${tableEntries}
\t},
};
`;
}
