/**
 * Codegen orchestrator. Reads content.schema.ts and writes:
 * - src/db/schema/generated/*
 * - src/db/cms-database.generated.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import {
	findEventsCollection,
	hasFieldKind,
	iterateCollections,
	iterateSingletons,
	type ContentSchemaRegistry,
} from '@steincms/cms/schema';
import { generateDbWiringSource } from './generate-db-wiring';
import {
	generateListCollectionSchema,
	generateRegistrationsWrapper,
	generateSchemaIndexExports,
	generateSingletonTypeNames,
	generateSingletonsSchema,
} from './field-to-drizzle';

const GENERATED_BANNER =
	'// AUTO-GENERATED by npm run db:sync-schema — do not edit.\n// Source: src/content.schema.ts\n\n';

const GENERATED_MODULES = ['singletons', 'registrations'] as const;

export type GenerateDbSchemasOptions = {
	contentSchema: ContentSchemaRegistry;
	schemaDir: string;
	dbDir: string;
};

export type GenerateDbSchemasResult = {
	listCollections: string[];
	singletons: string[];
	eventsCollectionId: string | null;
	writtenFiles: string[];
};

function writeFile(filePath: string, contents: string, writtenFiles: string[]): void {
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, contents, 'utf-8');
	writtenFiles.push(filePath);
}

export function generateDbSchemas(options: GenerateDbSchemasOptions): GenerateDbSchemasResult {
	const { contentSchema, schemaDir, dbDir } = options;
	const generatedDir = path.join(schemaDir, 'generated');
	const writtenFiles: string[] = [];
	const listCollections: string[] = [];
	const singletons: string[] = [];

	for (const { id, kind, def } of iterateCollections(contentSchema)) {
		if (kind === 'list') {
			listCollections.push(id);
			const generated = generateListCollectionSchema(id, def.record);
			writeFile(
				path.join(generatedDir, generated.fileName),
				GENERATED_BANNER + generated.source,
				writtenFiles,
			);
		}
	}

	for (const { id } of iterateSingletons(contentSchema)) {
		singletons.push(id);
	}

	const singletonTypes = generateSingletonTypeNames(singletons);
	writeFile(
		path.join(generatedDir, 'singletons.ts'),
		GENERATED_BANNER + generateSingletonsSchema(singletonTypes),
		writtenFiles,
	);

	const eventsCollection = findEventsCollection(contentSchema);
	const eventsCollectionId = eventsCollection?.id ?? 'events';
	writeFile(
		path.join(generatedDir, 'registrations.ts'),
		GENERATED_BANNER + generateRegistrationsWrapper(eventsCollectionId),
		writtenFiles,
	);

	writeFile(
		path.join(generatedDir, 'index.ts'),
		GENERATED_BANNER + generateSchemaIndexExports([...listCollections, ...GENERATED_MODULES]),
		writtenFiles,
	);

	writeFile(
		path.join(schemaDir, 'index.ts'),
		[
			GENERATED_BANNER.trim(),
			"export * from './generated';",
			"export { activityLog } from '@steincms/db/schema/activity-log';",
			'',
		].join('\n'),
		writtenFiles,
	);

	const hasRegistrations = Boolean(
		eventsCollection && hasFieldKind(eventsCollection.def.record, 'registrationForm'),
	);
	writeFile(
		path.join(dbDir, 'cms-database.generated.ts'),
		generateDbWiringSource({ listCollectionIds: listCollections, hasRegistrations }),
		writtenFiles,
	);

	return { listCollections, singletons, eventsCollectionId, writtenFiles };
}
