// AUTO-GENERATED by npm run db:sync-schema — do not edit.
// Source: src/content.schema.ts

import type { CmsDatabase, DatabaseConnection } from '@steincms/cms/storage/db-contract';
import { getDb } from './client';
import { posts, singletons } from './schema';

function openDatabase(): DatabaseConnection {
	return getDb() as unknown as DatabaseConnection;
}

export const cmsDatabase: CmsDatabase = {
	open: openDatabase,
	tables: {
		posts,
		singletons,
	},
};
